In [2]:
import torch

In [7]:
x = torch.arange(12)
print(x)
print(x.shape)
print(x.numel())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12


In [15]:
x=x.reshape(2,6)
x

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [16]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [18]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
x = torch.tensor([1.0,2,3,4])
y= torch.tensor([2,3,4,5])

x/y
x**y
torch.exp(x)

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])

In [34]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
print(X)
print(Y)
torch.cat((X,Y),dim=1) 
# 如果是三维的，dim可以为2，想象成两个3d的方块，两个竖着堆叠就是0维，侧着就是1维，往里放就是2维

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [35]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [47]:
print(X.sum())
print(X)
print(X[-1])
print(X[1:3])
X[1,2] = 19
X

tensor(69.)
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 19.,  7.],
        [ 8.,  9., 10., 11.]])

In [48]:
X[0:2,1:3]=-1
X

tensor([[ 0., -1., -1.,  3.],
        [ 4., -1., -1.,  7.],
        [ 8.,  9., 10., 11.]])

In [39]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a)
print(b)
# 形状不同都能相加，默认使用了广播机制，都将自己复制成3*2的矩阵
a+b

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [53]:
# 分配内存，类似c的指针
before = id(Y)
Y = Y+X
id(Y) == before
# Y做了操作以后内存是变了，成为了新的变量，如果要原地操作
Z = torch.zeros_like(Y) # 复制Y的矩阵，内容都为0
Z[:] = X+Y
Z # Z地址是不变的，相当于对Z内部的矩阵进行修改，而不是给一个新矩阵

# 如果后面没有重复使用X，可以X[:] = X+Y 或者 X+=Y 来减少内存开销

tensor([[ 2., -4., -1., 18.],
        [21., -3., -2., 39.],
        [44., 48., 52., 56.]])

In [62]:
# numpy和pytorch的互转
A = X.numpy()
A
B = torch.tensor(A)
B

# tensor标量和python标量互转

a = torch.tensor([3.4])
a.item(),float(a),int(a)

(3.4000000953674316, 3.4000000953674316, 3)

In [4]:
A = torch.arange(20).reshape((5,4))
A.T
B = A.clone # 重新分配内存，不然直接使用地址

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [7]:
A= torch.tensor([[1,2],[3,4]])
B = torch.tensor([[1,1],[1,1]])
A*B # 每一个元素按照位置直接乘，不是矩阵乘法
A*3

tensor([[ 3,  6],
        [ 9, 12]])

In [26]:
A = torch.arange(40,dtype=torch.float32).reshape((2,5,4))
A.shape,A.sum()
print(A.shape)
A

torch.Size([2, 5, 4])


tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [12]:
# 按照维度求和
# 按照第一个维度求和，类似torch.cat(x,y)拼接矩阵的第三个维度，是将两个块拼在一起从正面看还是一个方块
a_sum_axis_0 = A.sum(axis=0)
print(a_sum_axis_0.shape)
a_sum_axis_0

torch.Size([5, 4])


tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])

In [14]:
a_sum_axis_1 = A.sum(axis=2)
print(a_sum_axis_1.shape)
a_sum_axis_1

torch.Size([2, 5])


tensor([[  6,  22,  38,  54,  70],
        [ 86, 102, 118, 134, 150]])

In [32]:
A.sum()/A.numel() #均值
A.mean(axis=1)


tensor([[ 8.,  9., 10., 11.],
        [28., 29., 30., 31.]])

In [34]:
A.sum(axis=0,keepdims = True)  # 三维求和变为2维，想要保持维度不变，设置keepdims

tensor([[[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

In [42]:
print(A)
A.cumsum(axis=0)# 累加求和

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])


tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

In [46]:
x = torch.tensor([1,2,3])
y = torch.tensor([2,3,4])
torch.dot(x,y) # 向量点积

#或者这样也一样
torch.sum(x*y)

tensor(20)

In [53]:
A = torch.tensor([[1,2,3],[4,5,6]])
x = torch.tensor([1,1,1])
torch.mv(A,x) #矩阵和向量乘法  matrix vector mutiplication\
# mv时，自动将x从一维数组转为列向量，不需要自己将x转换

tensor([ 6, 15])

In [57]:
A = torch.tensor([[1,2,3],[4,5,6]])
B = torch.tensor([[1,1],[1,1],[1,1,]])
print(A)
print(B)
torch.mm(A,B) #矩阵和向量乘法   #matrix matrix mutiplication

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 1],
        [1, 1],
        [1, 1]])


tensor([[ 6,  6],
        [15, 15]])

In [59]:
# l2范数 norm，常用于表示向量的大小，所有元素平方和的开根号，和F范数一样，只不过F范数用于矩阵
u= torch.tensor([3.0,-4.0])
torch.norm(u)
u.norm()

tensor(5.)

In [60]:
#L1范数，所有向量元素绝对值的和
u.abs().sum()

tensor(7.)

In [61]:
#F范数
u = torch.ones((4,5))
u.norm()



tensor(4.4721)